### ISSUE TITLE
移除qconf的依赖

### ISSUE THREAD

**Issue by luw2007** [ireaderlab/zyredis#1]
作为一个redis/codis的客户端，使用qconf 并非必要条件。
是否考虑减少依赖，便于推广使用。

**Comment by xidianwlc** [comment]
使用qconf是为了最好的实现failover机制，传统的通过起一个线程和zookeeper通信来保证failover的方式对于有GIL的编程语言不是很合适！

**Comment by xidianwlc** [comment]
qconf依赖已经是非必须项了，可以使用配置参数传递的方式使用
